//This code was auto-generated by CustomObjectGenerator

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

public class Interactables_Door
{
  [MenuItem("GameObject/Custom Objects/Interactables/Door", false,0)]
  static void CreateDoor()
  {
      GameObject obj = PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath("Assets/CustomObjects/Door.prefab", typeof(GameObject))) as GameObject;
      PrefabUtility.UnpackPrefabInstance(obj, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
      Selection.activeGameObject = obj;
  }
}
