//This code was auto-generated by CustomObjectGenerator

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

public class Models_Human_Figure
{
  [MenuItem("GameObject/Custom Objects/Models/Human_Figure", false,0)]
  static void CreateHuman_Figure()
  {
      GameObject obj = PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath("Assets/CustomObjects/Human_Figure.prefab", typeof(GameObject))) as GameObject;
      PrefabUtility.UnpackPrefabInstance(obj, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
      Selection.activeGameObject = obj;
  }
}
