using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System.Text;
using System.IO;

public class CustomObjectGenerator : EditorWindow
{
    /// <summary>
    /// Name of the CustomObjectName
    /// </summary>
    string customObjectName;

    /// <summary>
    /// Category of Custom Object
    /// </summary>
    string customObjectCategory;

    /// <summary>
    /// GameObject that will be made as the custom object
    /// </summary>
    [SerializeField]
    GameObject customObject;

    //Get Window
    [MenuItem("Tools/Custom Object Generator")]
    public static void ShowWindow()
    {
        GetWindow<CustomObjectGenerator>("Custom Object Generator");
    }

    //Draw Window Elements
    public void OnGUI()
    {
        EditorGUILayout.LabelField("Enter name for Custom Object");
        customObjectName = EditorGUILayout.TextField(customObjectName);

        EditorGUILayout.Space(10);

        EditorGUILayout.LabelField("Enter file for Custom Object");
        customObjectCategory = EditorGUILayout.TextField(customObjectCategory);

        EditorGUILayout.Space(10);

        EditorGUILayout.LabelField("Enter Game Object you want to add as Custom Object");
        customObject = (GameObject)EditorGUILayout.ObjectField(customObject, typeof(GameObject), true);

        if(GUILayout.Button("Generate Custom Object"))
        {
            GenerateCustomObject();
        }
    }

    // Create the custom object reference and the script that will handle the menu item functionality
    void GenerateCustomObject()
    {
        string prefabPath = "Assets/CustomObjects/" + customObjectName + ".prefab";
        string scriptPath = "Assets/Editor/CustomObjectScripts/" + customObjectCategory + "_" + customObjectName + ".cs";

        if (!AssetDatabase.IsValidFolder("Assets/CustomObjects"))
        {
            Debug.Log(AssetDatabase.CreateFolder("Assets", "CustomObjects"));
        }
        PrefabUtility.SaveAsPrefabAsset(customObject,prefabPath);

        StringBuilder generatedCode = new StringBuilder();
        generatedCode.AppendLine("//This code was auto-generated by CustomObjectGenerator");
        generatedCode.AppendLine("");
        generatedCode.AppendLine("using System.Collections;");
        generatedCode.AppendLine("using System.Collections.Generic;");
        generatedCode.AppendLine("using UnityEngine;");
        generatedCode.AppendLine("using UnityEditor;");
        generatedCode.AppendLine("");
        generatedCode.AppendLine("public class " + customObjectCategory + "_" + customObjectName);
        generatedCode.AppendLine("{");
        generatedCode.AppendLine("  [MenuItem(\"GameObject/Custom Objects/" + customObjectCategory + "/" + customObjectName + "\", false,0)]");
        generatedCode.AppendLine("  static void Create" + customObjectName + "()");
        generatedCode.AppendLine("  {");
        generatedCode.AppendLine("      GameObject obj = PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath(\"" + prefabPath + "\", typeof(GameObject))) as GameObject;");
        generatedCode.AppendLine("      PrefabUtility.UnpackPrefabInstance(obj, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);");
        generatedCode.AppendLine("      Selection.activeGameObject = obj;");
        generatedCode.AppendLine("  }");
        generatedCode.AppendLine("}");

        if (!AssetDatabase.IsValidFolder("Assets/Editor/CustomObjectScripts"))
        {
            Debug.Log(AssetDatabase.CreateFolder("Assets/Editor", "CustomObjectScripts"));
        }

        File.Delete(scriptPath);
        File.WriteAllText(scriptPath, generatedCode.ToString(), Encoding.UTF8);
        AssetDatabase.ImportAsset(scriptPath);
        EditorUtility.DisplayDialog("Created", "Custom Object has been created.", "OK");
    }
}
